export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA';
export const SET_INITIAL_LOAD = 'SET_INITIAL_LOAD';
export const HANDLE_FIRST_NAME_CHANGE = 'HANDLE_FIRST_NAME_CHANGE';
export const HANDLE_LAST_NAME_CHANGE = 'HANDLE_LAST_NAME_CHANGE';
export const HANDLE_AGE_CHANGE = 'HANDLE_AGE_CHANGE';
export const HANDLE_PHONE_CHANGE = 'HANDLE_PHONE_CHANGE'
export const ADD_NEW_USER = 'ADD_NEW_USER';